name: Close PRs to Main

on:
  pull_request:
    branches:
      - main

jobs:
  close-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Set up GitHub CLI
        run: sudo apt-get install gh

      - name: Close PR to main branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr close ${{ github.event.pull_request.number }} --comment "Please submit this PR to the `test` branch, not `main`."
