name: Close PR to Main

# Trigger the workflow on pull requests to the 'main' branch
on:
  pull_request:
    branches:
      - main

jobs:
  close-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Close Pull Request
        uses: peter-evans/close-pull-request@v3
        with:
          comment: "Please submit this PR to the `test` branch, not `main`."
