name: Releases
on:
  push:
    branches:
      - main
    paths-ignore:
      - "data/**"
concurrency:
  group: "main-branch"
jobs:
  changelog:
    if: github.repository == 'VigneshDevHub/CampX'
    runs-on: ubuntu-latest
    # Add this permissions block
    permissions:
      contents: write
      pull-requests: write
    steps:
      # The rest of your workflow steps remain the same
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      # ... (rest of your steps)

      - name: Bump version number
        run: |
          npm version patch -m "Release version %s"
          git push origin "release-from-${{ github.sha }}"
        env:
          # Use GITHUB_TOKEN instead of PERSONAL_ACCESS_TOKEN
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ... (rest of your steps, using GITHUB_TOKEN instead of PERSONAL_ACCESS_TOKEN)
