name: Welcome Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
      - name: Add a Welcome Message
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "👋 Welcome! Thank you for your contribution. We will review your pull request shortly!"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
